apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis-sts
  serviceName: redis-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sts
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-redis
          image: redis:7.4
          command:
            - bash
            - "-c"
            - |
              set -ex
              # Generate server-id from Pod ordinal index.
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo "ordinal ${ordinal}"
              # Copy appropriate config files from config-map to emptyDir.
              mkdir -p /redis/conf/
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/redis-configmap/primary.conf /redis/conf/redis.conf
              else
                cp /mnt/redis-configmap/replica.conf /redis/conf/redis.conf
              fi
              cat /redis/conf/redis.conf
          volumeMounts:
            - name: redis-config-volume
              mountPath: /redis/conf/
            - name: redis-configmap-volume
              mountPath: /mnt/redis-configmap
      containers:
        - name: redis-container
          image: redis:7.4
          command: ["redis-server"]
          args: ["/redis/conf/redis.conf"]
          volumeMounts:
            - name: redis-config-volume
              mountPath: /redis/conf/
            - name: redis-pvc
              mountPath: /redis/data
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 750m
              memory: 2Gi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  role=$(redis-cli -h 127.0.0.1 info replication | grep "role:" | tr -d '\r' | cut -d':' -f2)
                  if [[ "$role" == "master" ]]; then
                    exit 0
                  else
                    #is master(leader) connect to other replicas(followers)
                    master_status=$(redis-cli -h 127.0.0.1 info replication | grep "master_link_status:" | tr -d '\r')
                    [[ "$master_status" == "master_link_status:up"* ]] || exit 1
                  fi
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: redis-configmap-volume
          configMap:
            name: redis-role-config
        - name: redis-config-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
